Chuyện người con gái Nam Xương (trích “Truyền kỳ mạn lục”) Việt Nam / Lớp 9 » Nguyễn Dữ

Nội dung

Vũ Thị Thiết, người con gái quê ở Nam Xương[1], tính đã thuỳ mị, nết na, lại thêm tư dung[2] tốt đẹp. Trong làng có chàng Trương Sinh, mến vì dung hạnh[3], xin với mẹ đem trăm lạng vàng cưới về. Song Trương Sinh có tính đa nghi, đới với vợ phòng ngừa quá sức. Nàng cũng giữ gìn khuôn phép, không từng để lúc nào vợ chồng phải đến thất hoà[4]. Cuộc xum vầy chưa được bao lâu thì xảy ra việc triều đình bắt lính đi đánh giặc Chiêm. Trương tuy con nhà hào phú[5] nhưng không có học, nên phải ghi trong sổ lính đi vào loại đầu. Buổi ra đi mẹ chàng có dặn rằng: - Nay con phải tạm ra tòng quân, xa lìa dưới gối. Tuy hội công danh từ xưa ít gặp, nhưng trong chỗ binh cách[6] phải biết giữ mình làm trọng, gặp khó nên lui, lường sức mà tiến, đừng nên tham miếng mồi thơm để lỡ mắc vào cạm bẫy. Quan cao tước lớn nhường để người ta. Có như thế, mẹ ở nhà mới khỏi lo lắng vì con được. Chàng quỳ xuống đất vâng lời dạy. Nàng rót chén rượu đầy tiễn chồng mà rằng: - Chàng đi chuyến này, thiếp chẳng dám mong đeo được ấn phong hầu, mặc áo gấm[7] trở về quê cũ, chỉ xin ngày về mang theo được hai chữ bình yên, thế là đủ rối. Chỉ e việc quân khó liệu, thế giặc khôn lường. Giặc cuồng còn lẩn lút, quân triều còn gian lao, rồi thế chẻ tre chưa có, mà mùa dưa chín quá kì[8], khiến cho tiện thiếp[9] băn khoăn, mẹ hiền lo lắng. Nhìn trăng soi thành cũ, lại sửa soạn áo rét, gửi người ải xa, trông liễu rũ bãi hoang, cũng sợ không có cánh hồng bay bổng. Nàng nói đến đây, mọi người đều ứa hai hàng lệ. Rồi đó, tiệc tiễn vừa tàn, áo chàng đành rứt. Nước mắt cảnh vật vẫn còn như cũ, mà lòng người đã nhuộm mối tình, muôn dặm quan san[10]! Bấy giờ, nàng đương có mang, sau khi xa chồng vừa đầy tuần[11] thì sinh ra một đưa con trai, đặt tên là Đản. Ngày qua tháng lại, thoắt đã nửa năm, mỗi khi thấy bướm lược đầy vườn, mây che kín núi, thì nỗi buồn gốc bể chân trời không thể nào ngăn được. Bà mẹ cũng vì nhớ con mà dần sinh ốm. Nàng hết sức thuốc than lễ bế thần phật và lấy lời ngọt ngào khôn khéo khuyên lơn. Song bệnh tình mỗi ngày một trầm trọng, bà biết không sống được, bèn trối[12] lại với nàng rằng: - Ngắn dài có số, tươi héo bởi trời. Mẹ không phải không muốn đợi chồng con về, mà

không gắng ăn miếng cơm miếng cháo đặng cùng vui sum họp. Song, làm tham vô cùng mà vận trời khó tránh. Nước hết chuông rền[13], số cùng khí kiệt[14]. Một tấm thân tàn, nguy trong sớm tối, việc sống chết không khỏi phiền đến con. Chồng con nơi xa xôi không biết sống chết thế nào không thể về đền ơn được. Sau này, trời xét lòng lành, ban cho phúc đức, giống dòng tươi tốt, con cháu đông đàn, xanh kia quyết chẳng phụ con, cũng như con đã chẳng phụ mẹ. Bà cụ nói xong thì mất. Nàng hết lời thương xót, phàm việc ma chay tế lễ, lo liệu như đối với cha mẹ đẻ của mình. Qua năm sau, giặc ngoan cố chịu trói, việc quân kết thúc. Trương Sinh về tới nhà, được biết mẹ đã qua đời, con vừa học nói. Chàng hỏi mồ mẹ, rồi bế đứa con nhỏ đi thăm; đứa trẻ không chịu, ra đến đồng, nó quấy khóc, Sinh dỗ dành: - Nín đi con, đừng khóc. Cha về, bà đã mất, lòng cha buồn khổ lắm rồi.

Đứa con ngây thơ nói: - Ô hay! Thế ra ông cũng là cha tôi ư! Ông lại biết nói chứ không như cha tôi trước kia chỉ nín thin thít. Chàng ngạc nhiên gạn hỏi. Đứa con nhỏ nói: - Trước đây, thường có một người đàn ông, đêm nào cũng đến, mẹ Đản đi cũng đi, mẹ Đản ngồi cũng ngồi, nhưng chẳng bao giờ bế Đản cả. Tính chàng hay ghen, nghe con nói vậy, đinh ninh là vợ hư, mối nghi ngờ ngày càng sâu, không có gì gỡ ra được. Về đến nhà, chàng la um lên cho hả giận. Vợ chàng khóc mà rằng: - Thiếp vốn con kẻ khó, được nương tựa nhà giàu. Sum hợp chưa thoả tình chăn gối, chia phôi vì động việc lửa binh. Cách biệt ba năm giữ gìn một tiết[15]. Tô son điểm phấn từng đã nguôi lòng, ngõ liễu tường hoa[16] chưa hề bén gót. Đâu có sự mất nết hư thân như lời chàng nói. Dám xin bày tỏ để cởi mối nghi ngờ. Mong chàng đừng một mực nghi oan cho thiếp. Chàng vẫn không tin. Nhưng nàng hỏi chuyện kia do ai nói ra, thì lại giấu không kể lời con nói; chỉ lấy chuyện bóng gió này nọ mà mắng nhiếc nàng, và đánh đuổi đi. Họ hàng làng xóm bênh vực và biện bạch cho nàng, cũng chẳng ăn thua gì cả. Nàng bất đắc dĩ nói: - Thiếp sở dĩ nương tựa vào chàng vì có cái thú vui nghi gia nghi thất[17]. Nay đã bình rơi trâm gãy, mây tạnh mưa tan, sen rũ trong ao, liễu tàn trước gió; khóc tuyết bông hoa rụng cuống, kêu xuân cái én lìa đàn, nước thẳm buồm xa, đâu còn có thể lại lên núi Vọng Phu kia nữa[18].

Đoạn rồi nàng tắm gội sạch, ra bến Hoàng Giang ngửa mặt lên trời mà than rằng: - Kẻ bạc mệnh này duyên phận hẩm hiu, chồng con rẫy bỏ, điều đâu bay buộc, tiếng chịu nhuốc nhơ, thần sông có linh, xin ngài chứng giám. Thiếp nếu đoan trang giữ tiết, trinh bạch gìn lòng, vào nước xin làm ngọc Mỵ Nương[19], xuống đất xin làm cỏ Ngu mĩ[20]. Nhược bằng lòng chim dạ cá[21], lừa chồng dối con, dưới xin làm mồi cho cá tôm, trên xin làm cơm cho diều quạ, và xin chịu khắp mọi người phỉ nhổ. Nói xong nàng gieo mình xuống sông mà chết. Chàng tuy giận là nàng thất tiết, nhưng thấy nàng tự tận[22] cũng động lòng thương, tìm vớt thây nàng, nhưng chẳng thấy tăm hơi đâu cả. Một đêm phòng không vắng vẻ, chàng ngồi dưới ngọn đèn khuya, chợt đứa con nói rằng: - Cha Đản lại đến kia kìa! Chàng hỏi đâu. Nó chỉ bóng chàng ở trên vách: - Đây này! Thì ra, ngày thường, ở một mình, nàng hay đùa con, trỏ bóng mình mà bảo là cha Đản. Bấy giờ chàng mới tỉnh ngộ, thấu nỗi oan của vợ, nhưng việc trót đã qua rồi!

Cùng làng với nàng, có người tên là Phan Lang, khi trước làm đầu mục[23] ở bến đò Hoàng Giang, một đêm chiêm bao thấy người con gái áo xanh đến kêu xin tha mạng. Sáng dậy, Phan Lang thấy có người phường chài đem vào biếu một con rùa mai xanh, sực nghĩ đến chuyện mộng, bèn đem thả con rùa ấy. Cuối đời Khai Đại[24] nhà Hồ, quân Minh mượn tiếng đưa Trầm Thiêm Bình[25] về nước, phạm vào cửa ải Chi Lăng, nhân dân trong nước, nhiều người sợ hãi phải chạy trốn ra ngoài bể, không may đắm thuyền đều chết đuối cả. Thây Phan Lang dạt vào một cái động rùa ở hải đảo, có người đàn bà là Linh Phi trông thấy nói rằng: - Đây là vị ân nhân cứu sống ta thuở xưa. Linh Phi bèn lấy khăn dấu mà lau, lấy thuốc thần mà đổ, một chốc Phan Lang liền tỉnh lại. Phan trông thấy cung gấm đền dao[26] thật nguy nga lộng lẫy, mà chưa biết mình đã lọt vào cung nước của rùa thần. Linh Phi bấy giờ mình mặc áo gấm dát ngọc, chân đi giày có vân nạm vàng, cười bảo Phan Lang rằng: - Tôi là Linh Phi trong động rùa, vợ vua biển Nam Hải, nhớ hồi còn nhỏ đi chơi ở bến sông bị người phường chài bắt được, ngẫu nhiên báo mộng, quả được nhờ ơn. Gặp gỡ ngày nay, há chẳng phải lòng trời xui khiến cho tôi có dịp đền ơn trả nghĩa? Phi bèn đặt yến ở gác Triêu Dương để thết đãi Phan Lang. Dự tiệc hôm ấy có vô số

những mĩ nhân, quần áo thướt tha, mái tóc búi xễ. Trong số đó, có một người mặt chỉ hơi điểm qua một chút son phấn trông rất giống Vũ Nương. Phan có ý nhìn trộm, nhưng không dám nhận. Tiệc xong, người đàn bà ấy nói với Phan Lang rằng: - Tôi với ông vốn người cùng làng, cách mặt chưa bao, đã quên nhau rồi ư? Bấy giờ Phan mới nhận đích người ấy là Vũ Nương và gạn hỏi duyên cớ. Nàng nói: - Tôi ngày trước không may bị người vu oan, phải gieo mình xuống sông tự tử. Các nàng tiên trong cung nước thương tôi cô tội, rẽ một đường nước cho tôi thoát chết, nếu không thì đã vùi vào bụng cá, còn đâu mà gặp ông. Phan nói: - Nương Tử[27] nghĩa khác Tào Nga[28], hờn không Tinh Vệ[29] mà phải ôm mối hận gieo mình xuống nước. Nay thóc cũ không còn, thóc mới vừa gặt[30], há lại không tưởng nhớ đến quê hương ư? Vũ Nương nói: - Tôi bị chồng ruồng rẫy, thà già ở chốn làng mây cung nước, chứ còn mặt mũi nào về nhìn thấy người ta nữa!

Phan nói: - Nhà cửa tiên nhân[31] của nương tử, cây cối thành rừng, phần mộ tiên nhân của nương tử, cỏ gai rợp mắt. Nương tử dù không nghĩ đến, nhưng tiên nhân còn mong đợi nương tử thì sao? Nghe đến đây, Vũ Nương ứa nước mắt khóc, rồi quả quyết đổi giọng mà rằng: - Có lẽ không thể gửi hình ẩn bóng ở đây được mãi, để mang tiếng xấu xa. Phải chăng, ngựa Hồ gầm gió bắc, chim Việt đậu cành nam[32]. Cản vì nỗi ấy, tôi tất phải tìm về có ngày. Hôm sau, Linh Phi lấy một cái túi bằng lụa tía, đựng mười hạt minh châu, sai sứ giả Xích Hỗn[33] đưa Phan ra khỏi nước. Vũ Nương nhân đó cũng đưa gửi một chiếc hoa vàng mà dặn: - Nhờ nói hộ với chàng Trương, nếu còn nhớ chút tình xưa nghĩa cũ, xin lập một đàn giải oan ở bến sông, đốt cây đèn thần chiếu xuống nước, tôi sẽ trở về. Lúc đến nhà, Phan đem chuyện kể lại với họ Trương. Ban đầu Trương không tin. Nhưng khi nhận được chiếc hoa vàng, chàng mới sợ hãi mà nói: - Đây quả là vật dùng mà vợ tôi mang lúc ra đi. Chàng bèn theo lời, lập một đàn tràng ba ngày đêm ở bến Hoàng Giang. Rồi quả thấy

Vũ Nương ngồi trên một chiếc kiệu hoa đứng ở giữa dòng, theo sau có đến năm mươi chiếc xe cờ tán, võng lọng, rực rỡ đầy sông, lúc ẩn, lúc hiện. Chàng vội gọi, nàng vẫn ở giữa dòng mà nói vọng vào: - Thiếp cảm ơn đức của Linh Phi, đã thề sống chết cũng không bỏ. Đa tạ tình chàng, thiếp chẳng thể trở về nhân gian được nữa. Rồi trong chốc lát, bóng nàng loang loáng mờ nhạt dần mà biến đi mất.

Giải nghĩa từ khó

[1] Nam Xương: Nay thuộc huyện Lí Nhân, tỉnh Hà Nam. [2] Tư dung: dáng vẻ và nhan sắc. [3] Dung hạnh: nhan sắc và đức hạnh. [4] Thất hoà: mất sự hoà thuận (thất: để mất). [5] Hào phú: nhà giàu và có thế lực. [6] Binh cách: việc quân sự, việc chiến tranh. Chỗ binh cách: nơi chiến trận. [7] Đeo ấn phong hầu, mặc áo gấm: ý nói được làm quan to, được ban ấn (con dấu vua ban) và áo may bằng gấm quý. [8] Mùa dưa chín quá kì; ngày xưa, người đi lính thú, cứ đến mùa dưa chín thì được thay phiên để về nhà. Câu này ý nói sợ kì hạn đã qua mà chồng vẫn chẳng được về. [9] Tiện thiếp: cách xưng hô khiêm tốn của người phụ nữ ngày xưa [10] Quan san: chỉ nơi xa xôi (quan: cửa ải, san hay sơn: núi). [11] Tuần: đơn vị tính thời gian xưa. Tuần gồm 10 ngày. Một tháng có 3 tuần: thượng, trung và hạ tuần. [12] Trối: lời dặn dò cuối cùng của người sắp chết. [13] Nước hết chuông rền: người xưa dùng đồng hồ nước để đo thời gian. Khi nước chảy nhỏ giọt hết cũng tức là lúc chuông báo sáng để bắt đầu một ngày mới. Ở đây ý nói thời gian qua nhanh, đời người đã đến lúc kết thúc. [14] Số cùng khí kiệt: số mệnh đã hết, sức lực đã cạn. [15] Một tiết: ý nói giữ trọn lòng chung thuỷ với chồng (tiết: danh dự và phẩm giá con người). [16] Ngõ liễu tường hoa: chỉ nơi có những chuyện quan hệ trai gái không đứng đắn.

[17] Nghi gia nghi thất: nên cửa nên nhà, ý nói thành vợ thành chồng, cùng gây dựng hạnh phúc gia đình. [18] Cả đoạn “Nay đã bình rơi tâm gãy... núi Vọng Phu kia nữa”: ý nói nỗi thất vọng của Vũ Nương khi bị Trương Sinh hắt hủi, tình vợ chồng gắn bó lâu nay đã tan vỡ. [19] Ngọc Mị Nương: theo tích ngọc trai giếng nước trong truyền thuyết Mị Châu – Trọng Thuỷ, ý nói đến chết vẫn giữ lòng trong sáng. [20] Cỏ Ngu mĩ: tích về nàng Ngu Cơ, vợ Hạng Vũ. Khi Hạng Vũ thua trận, thế cùng, chạy đến Cai Hạ, nàng rút gươm tự vẫn. Tương truyền hồn Ngu Cơ hoá thành hai khóm cỏ trên mộ, ngày đêm cứ quấn quít vào nhau, người ta gọi cỏ Ngu mĩ nhân, ý nói đến chết vẫn giữ lòng chung thuỷ. [21] Lòng chim dạ cá: ở đây ý nói thay lòng đổi dạ, không chung thuỷ. [22] Tự tận: tự kết liễu đời mình, đồng nghĩa với tự vẫn, tự sát. [23] Đầu mục: chức quan cai trị nhỏ ở địa phương. [24] Khai Đại: niên hiệu thứ hai của Hồ Hán Thương (1403 – 1407). [25] Trần Thiêm Bình: tên đại Việt gian đời Hồ, theo giặc Minh. [26] Đền dao: đền bằng ngọc dao, ý nói cung điện, đền đài thật sang trọng. [27] Nương tử: từ dùng để chỉ hoặc gọi người phụ nữ một cách tôn kính. [28] Tào Nga: một cô gái đời Hán nhảy xuống sông vớt xác cha không được đã tự tử luôn, khi xác nổi lên, người ta thấy nàng ôm được thây cha. [29] Tinh Vệ: con gái vua Viêm Đế chết đuối, hoá thành chim Tinh Vệ ngậm đá toan lấp biển. Cả hai điển tích đều muốn nói: Vũ Nương chết vì bị nghi oan, khác cái chết của hai người con gái nói trên, có ý khuyên nàng nghĩ đến quê hương, gia đình, chồng con. [30] Thóc cũ không còn, thóc mới vừa gặt: ý nói đã tròn một năm, mùa này đã tiếp mùa khác. [31] Tiên nhân: người đời trước mình, chỉ cha ông, tổ tiên. Từ tiên nhân ở câu sau lại có ý chỉ Trương Sinh. [32] Ngựa Hồ gầm gió bắc, chim Việt đậu cành nam: đất Hồ ở phương Bắc lắm ngựa quý, đất Việt ở phương nam (Trung Quốc) lắm chim lạ. Dù ở đâu thì ngựa Hồ mỗi khi thấy gió bắc lại hí lên, chim Việt vẫn nhớ khí hậu ấm áp phương nam nên vẫn tìm đến cành cay phía nam để đậu. ý nói vẫn nhớ nước cũ, quê cũ.

[33] Xích Hỗn: tên của sứ giả được Linh Phi sai đưa Phan Lan ra khỏi thuỷ cung trở về cõi trần (xích: đỏ, hỗn: một loại cá quả).

Truyền kì mạn lục (Ghi chép tản mạn những điều kì lạ vẫn được lưu truyền) viết bằng chữ Hán, khai thác các truyện cổ dân gian và các truyền thuyết lịch sử, dã sử của Việt Nam. Nhân vật chính thường là những người phụ nữ đức hạnh, khao khát một cuộc sống yên bình, hạnh phúc, nhưng các thế lực bạo tàn và cả lễ giáo khắc nghiệt lại xô đẩy họ vào những cảnh ngộ éo le, oan khuất, bất hạnh. Một loại nhân vật khác là những người trí thức có tâm huyết, bất mãn với thời cuộc, không chịu trói mình trong vòng danh lợi chật hẹp. Chuyện người con gái Nam Xương là một trong hai mươi truyện của tác phẩm này. Nguồn: Nguyễn Dữ, Truyền kì mạn lục, bản dịch của Trúc Khê Ngô Văn Triện, NXB Văn hoá, Hà
